/* ==========================================================
   QUESTION BANK  -  js/questions.js
   ----------------------------------------------------------
   HOW TO CUSTOMIZE (to match your instructor's lessons):
   - Each question is one line: q(text, [A, B, C, D], answerIndex, explanation)
   - answerIndex is 0 for A, 1 for B, 2 for C, 3 for D.
   - Add, edit, or delete questions freely. The quiz engine counts
     them automatically (keep at least 20 per subject).
   - Answer choices are shuffled automatically on every attempt.
   - Use "\n" inside text to start a new line (useful for code).
   ========================================================== */

function q(text, choices, answer, explanation) {
  return { q: text, choices: choices, answer: answer, explanation: explanation };
}

window.QUIZ_DATA = {

  /* ======================= 1. APPLICATION DEVELOPMENT ======================= */
  "application-development": {
    name: "Application Development",
    questions: [
      q("What does SDLC stand for?",
        ["System Design Logic Cycle", "Software Development Life Cycle", "Structured Data Language Control", "Software Deployment Lifecycle Chart"], 1,
        "SDLC is the Software Development Life Cycle: the series of phases used to plan, build, test, and maintain software."),
      q("Which SDLC phase is usually done first?",
        ["Testing", "Deployment", "Planning and requirements gathering", "Maintenance"], 2,
        "You must understand what the users need before you can design, build, or test anything, so planning and requirements come first."),
      q("Which of the following is a FUNCTIONAL requirement?",
        ["The system must load a page within 3 seconds", "The system must be available 99% of the time", "The system must let a student submit a quiz and show the score", "The system must be easy to learn"], 2,
        "A functional requirement describes what the system does (a feature). The other options describe quality or performance, which are non-functional requirements."),
      q("\"The website must work on phones, tablets, and laptops.\" What kind of requirement is this?",
        ["Non-functional requirement", "Functional requirement", "Database requirement", "Testing requirement"], 0,
        "It describes a quality of the system (compatibility and usability) rather than a specific feature, so it is non-functional."),
      q("Which statement best describes the Waterfall model?",
        ["Work is done in short repeating sprints with constant feedback", "Phases are completed one after another in a fixed order", "The software is never tested", "Requirements change every day by design"], 1,
        "Waterfall is sequential: requirements, design, implementation, testing, deployment, and maintenance, each finishing before the next begins."),
      q("A key idea of Agile development is:",
        ["Writing all documentation before any coding", "Delivering working software in small increments and adapting to feedback", "Avoiding communication with customers", "Testing only at the very end"], 1,
        "Agile builds software in small iterations (sprints) and welcomes changing requirements and frequent customer feedback."),
      q("What is a wireframe?",
        ["A finished, fully coded web page", "A simple layout sketch showing where elements go on a screen", "A type of network cable", "A database backup file"], 1,
        "Wireframes are low-detail blueprints of screens used in UI design before any styling or coding happens."),
      q("Which statement correctly compares UI and UX?",
        ["UI is how the product looks and is operated; UX is the overall experience of using it", "UI and UX mean exactly the same thing", "UX is only about colors; UI is only about databases", "UI is the backend; UX is the server"], 0,
        "UI (user interface) covers visual elements such as buttons and layout, while UX (user experience) covers how easy and pleasant the whole interaction is."),
      q("Testing individual functions or methods in isolation is called:",
        ["Integration testing", "User acceptance testing", "Unit testing", "Stress testing"], 2,
        "Unit tests check the smallest parts of a program (functions, methods, classes) one at a time."),
      q("Which testing checks that different modules work correctly TOGETHER?",
        ["Unit testing", "Integration testing", "Syntax checking", "Compiling"], 1,
        "Integration testing verifies the interaction between combined modules, such as a form talking to a database."),
      q("User Acceptance Testing (UAT) is performed mainly by:",
        ["The compiler", "The database administrator only", "The end users or client", "The network provider"], 2,
        "UAT lets real users or the client confirm that the finished system meets their needs before it is released."),
      q("What is debugging?",
        ["Writing documentation", "Finding and fixing errors in a program", "Designing the database", "Uploading the app to a server"], 1,
        "Debugging is the process of locating the cause of a defect (bug) and correcting it."),
      q("In black-box testing, the tester:",
        ["Reads and edits every line of source code", "Checks inputs and outputs without looking at the internal code", "Only tests the database", "Tests only the colors of the interface"], 1,
        "Black-box testing treats the program as a closed box and focuses on whether the output matches the expected result for a given input."),
      q("What is deployment?",
        ["Gathering user requirements", "Making the finished application available for real users to use", "Drawing a flowchart", "Deleting old code"], 1,
        "Deployment is releasing the application to its production environment (a server, an app store, etc.) so that users can access it."),
      q("Fixing a bug that users reported after the software was released is called:",
        ["Adaptive maintenance", "Perfective maintenance", "Corrective maintenance", "Preventive design"], 2,
        "Corrective maintenance repairs defects found after release. Adaptive maintenance adjusts to new environments; perfective improves features."),
      q("In database applications, what does CRUD stand for?",
        ["Copy, Run, Update, Delete", "Create, Read, Update, Delete", "Connect, Retrieve, Upload, Display", "Create, Remove, Undo, Download"], 1,
        "CRUD lists the four basic data operations that most applications perform: Create, Read, Update, Delete."),
      q("Which SQL statement is used to retrieve data from a table?",
        ["INSERT", "UPDATE", "DELETE", "SELECT"], 3,
        "SELECT reads data. INSERT adds rows, UPDATE changes rows, and DELETE removes rows."),
      q("What is the purpose of a primary key in a database table?",
        ["To make the table look nicer", "To uniquely identify each record", "To encrypt the table", "To store the user's password"], 1,
        "A primary key holds a unique, non-null value for every row so each record can be identified exactly."),
      q("Why do developers use a version control system such as Git?",
        ["To make programs run faster", "To track changes to code and let teams collaborate safely", "To design user interfaces", "To replace testing"], 1,
        "Version control records the history of changes, lets you undo mistakes, and helps team members merge their work."),
      q("Which task belongs to the DESIGN phase of the SDLC?",
        ["Deciding the screens, database structure, and system architecture", "Fixing bugs reported by users", "Interviewing users about their needs", "Releasing the software to the public"], 0,
        "In the design phase, the team plans how the system will be built: interfaces, data models, and architecture.")
    ]
  },

  /* ============================= 2. NETWORKING ============================= */
  "networking": {
    name: "Networking",
    questions: [
      q("What is a computer network?",
        ["A single computer with many programs", "Two or more connected devices that can share data and resources", "A type of software license", "A printer driver"], 1,
        "A network links devices (computers, printers, phones) so they can communicate and share resources."),
      q("In which topology is every device connected to one central device such as a switch?",
        ["Bus", "Ring", "Star", "Mesh"], 2,
        "A star topology connects all nodes to a central hub or switch. If one cable fails, only that device is affected."),
      q("What is the main weakness of a bus topology?",
        ["It is too expensive", "A break in the main backbone cable can bring down the network", "It cannot connect more than two computers", "It uses wireless only"], 1,
        "All devices share one backbone cable, so damage to it can disrupt the entire segment."),
      q("Which topology gives the most redundancy because devices have multiple paths to each other?",
        ["Mesh", "Bus", "Star", "Linear"], 0,
        "In a mesh topology, devices connect to several others, so traffic can be rerouted if a link fails (at a higher cost)."),
      q("How many layers does the OSI model have?",
        ["4", "5", "6", "7"], 3,
        "The OSI model has seven layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application."),
      q("Which OSI layer is responsible for logical addressing and routing (IP)?",
        ["Data Link layer", "Network layer", "Transport layer", "Session layer"], 1,
        "The Network layer (Layer 3) uses IP addresses to route packets between networks."),
      q("How many layers does the TCP/IP model commonly have?",
        ["4", "7", "3", "8"], 0,
        "TCP/IP is usually described with four layers: Network Access (Link), Internet, Transport, and Application."),
      q("How many bits are in an IPv4 address?",
        ["16", "32", "64", "128"], 1,
        "IPv4 addresses are 32 bits long, written as four decimal numbers (octets) such as 192.168.1.1. IPv6 uses 128 bits."),
      q("Which IPv4 address class has a first octet in the range 1 to 126?",
        ["Class A", "Class B", "Class C", "Class D"], 0,
        "Class A: 1-126, Class B: 128-191, Class C: 192-223. (127 is reserved for loopback.)"),
      q("What is the default subnet mask of a Class C network?",
        ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"], 2,
        "Class C uses 24 network bits, which is 255.255.255.0."),
      q("Which of these is a private IP address?",
        ["8.8.8.8", "172.217.5.1", "203.0.113.5", "192.168.1.10"], 3,
        "Private ranges are 10.0.0.0/8, 172.16.0.0 to 172.31.255.255, and 192.168.0.0/16. The others are public addresses."),
      q("What is the main job of a router?",
        ["Repeat signals to every port", "Forward packets between different networks", "Store web pages", "Convert digital signals to paper"], 1,
        "A router connects separate networks (for example, your LAN and the Internet) and chooses the best path for packets."),
      q("How does a switch differ from a hub?",
        ["A switch sends data only to the destination port using MAC addresses; a hub sends it to all ports", "A switch is slower and sends data everywhere", "A hub is smarter than a switch", "They are exactly the same"], 0,
        "A switch learns MAC addresses and forwards frames to the right port, which reduces collisions. A hub blindly repeats data to all ports."),
      q("A hub works mainly at which OSI layer?",
        ["Network layer", "Physical layer", "Application layer", "Transport layer"], 1,
        "A hub is a simple repeater that regenerates electrical signals, so it operates at the Physical layer (Layer 1)."),
      q("Which statement describes TCP?",
        ["Connectionless and does not guarantee delivery", "Connection-oriented and provides reliable, ordered delivery", "Used only for wireless networks", "A hardware device"], 1,
        "TCP sets up a connection, acknowledges data, and retransmits lost segments, which makes it reliable."),
      q("Which application is MOST suited to UDP?",
        ["Downloading a bank statement", "Live video streaming or online gaming", "Sending a signed contract by email", "Transferring files that must be perfect"], 1,
        "UDP is fast and connectionless with low overhead. Real-time apps tolerate a few lost packets in exchange for speed."),
      q("A network that covers a small area such as a school computer lab is a:",
        ["WAN", "MAN", "LAN", "GAN"], 2,
        "A LAN (Local Area Network) covers a limited area such as a room, building, or campus."),
      q("A network that spans a city or large campus is usually called a:",
        ["PAN", "MAN", "LAN", "SAN"], 1,
        "A MAN (Metropolitan Area Network) is larger than a LAN but smaller than a WAN, typically covering a city."),
      q("Which of the following is the best example of a WAN?",
        ["A home Wi-Fi network", "Bluetooth between a phone and earbuds", "The Internet", "A single USB cable"], 2,
        "A WAN (Wide Area Network) covers large geographic areas. The Internet is the largest WAN."),
      q("Which command is commonly used to test whether another host is reachable?",
        ["ping", "format", "compile", "print"], 0,
        "ping sends ICMP echo requests and reports whether replies are received and how long they take.")
    ]
  },

  /* ====================== 3. OBJECT-ORIENTED PROGRAMMING ====================== */
  "oop": {
    name: "Object-Oriented Programming (OOP)",
    questions: [
      q("In OOP, a class is best described as:",
        ["A running instance of a program", "A blueprint or template for creating objects", "A kind of loop", "A file extension"], 1,
        "A class defines the attributes and methods that its objects will have. Objects are created from it."),
      q("An object is:",
        ["The same thing as a class", "An instance of a class", "A Java keyword", "A comment in the code"], 1,
        "An object is a concrete instance of a class with its own data values, for example one particular Student."),
      q("Which Java keyword creates a new object?",
        ["create", "new", "make", "object"], 1,
        "Example: Student s = new Student(); The new keyword allocates memory and calls the constructor."),
      q("Attributes of a class (also called fields) store:",
        ["The behavior of the object", "The state or data of the object", "The name of the file", "Only static text"], 1,
        "Attributes are variables that hold an object's data, such as name and grade. Methods define behavior."),
      q("What is a method?",
        ["A variable that stores a number", "A block of code in a class that performs an action", "A type of constructor only", "A package"], 1,
        "Methods define what an object can do, for example calculateAverage() or displayInfo()."),
      q("Which statement about constructors in Java is TRUE?",
        ["They must have a return type of void", "They have the same name as the class and no return type", "They are called manually after the object is used", "A class can have only one constructor"], 1,
        "A constructor shares the class name and has no return type. It runs automatically when you use new, and a class may have several (overloaded) constructors."),
      q("What happens if you do NOT write any constructor in a Java class?",
        ["The code will not compile", "Java provides a default no-argument constructor", "The class becomes abstract", "Objects cannot be created"], 1,
        "If no constructor is declared, the compiler adds a default constructor with no parameters."),
      q("In Java, the keyword this refers to:",
        ["The parent class", "The current object", "The main method", "A static variable only"], 1,
        "this refers to the object whose method or constructor is running. It is often used to separate a field from a parameter with the same name."),
      q("Encapsulation is best achieved by:",
        ["Making all fields public", "Making fields private and providing public getters and setters", "Using only static methods", "Avoiding classes"], 1,
        "Encapsulation hides internal data and exposes controlled access, so the object can protect its own state."),
      q("Which access modifier allows access only within the same class?",
        ["public", "protected", "private", "default (no modifier)"], 2,
        "private members are visible only inside the class where they are declared."),
      q("Which access modifier allows access from anywhere?",
        ["private", "public", "protected", "final"], 1,
        "public members can be accessed from any other class."),
      q("A protected member can be accessed by:",
        ["Only its own class", "Its own package and subclasses", "Nobody", "Only the main method"], 1,
        "protected allows access within the same package and in subclasses, even if they are in a different package."),
      q("Which keyword is used for a class to inherit from another class in Java?",
        ["implements", "inherits", "extends", "super"], 2,
        "class Dog extends Animal means Dog inherits the members of Animal."),
      q("What does the super keyword do?",
        ["Creates a second object", "Refers to the parent (superclass) members or constructor", "Makes a variable constant", "Deletes the object"], 1,
        "super() calls the parent constructor and super.method() calls the parent's version of a method."),
      q("Having several methods with the same name but different parameter lists in one class is called:",
        ["Method overriding", "Method overloading", "Encapsulation", "Inheritance"], 1,
        "Overloading (compile-time polymorphism) differs by the number or type of parameters."),
      q("A subclass providing its own version of a method that exists in its parent class is:",
        ["Overloading", "Overriding", "Encapsulation", "Overwriting a file"], 1,
        "Overriding (runtime polymorphism) replaces the inherited implementation with a new one that has the same signature."),
      q("Which statement about an abstract class in Java is TRUE?",
        ["It can be instantiated with new", "It cannot be instantiated directly and may contain abstract methods", "It cannot have any methods", "It must be private"], 1,
        "Abstract classes are meant to be extended. They can mix complete methods with abstract ones that subclasses must implement."),
      q("Which keyword is used by a class to implement an interface?",
        ["extends", "implements", "uses", "interface"], 1,
        "class Circle implements Shape means Circle must provide the methods declared in the Shape interface."),
      q("Java does NOT allow a class to extend more than one class. Why does Java use interfaces?",
        ["To allow a class to follow multiple contracts without multiple class inheritance", "Because interfaces are faster", "To avoid using methods", "Because Java has no inheritance"], 0,
        "A class can implement many interfaces, which gives flexibility while avoiding the ambiguity problems of multiple class inheritance."),
      q("What is the output of this code?\n\nclass Animal { void sound() { System.out.println(\"Some sound\"); } }\nclass Dog extends Animal { void sound() { System.out.println(\"Bark\"); } }\n\nAnimal a = new Dog();\na.sound();",
        ["Some sound", "Bark", "Compile error", "Nothing is printed"], 1,
        "This is runtime polymorphism: the object is really a Dog, so the overridden Dog.sound() runs even though the variable type is Animal.")
    ]
  },

  /* =================== 4. AUTOMATA THEORY AND FORMAL LANGUAGES =================== */
  "automata-theory": {
    name: "Automata Theory and Formal Languages",
    questions: [
      q("In automata theory, an alphabet (Σ) is:",
        ["Any infinite set of strings", "A finite, non-empty set of symbols", "A set of states", "A regular expression"], 1,
        "Example: Σ = {0, 1} or Σ = {a, b, c}. Strings are built from the symbols of an alphabet."),
      q("A string is:",
        ["A finite sequence of symbols from an alphabet", "A set of alphabets", "A type of automaton", "A transition"], 0,
        "For Σ = {a, b}, strings include a, ab, bba, and so on."),
      q("What is the length of the string 0110?",
        ["3", "4", "5", "2"], 1,
        "Length is the number of symbols: 0, 1, 1, 0 gives 4."),
      q("What is the length of the empty string ε?",
        ["1", "0", "undefined", "Infinite"], 1,
        "The empty string contains no symbols, so |ε| = 0."),
      q("Σ* (Sigma star) represents:",
        ["Only the empty string", "All strings over Σ, including ε", "All strings of length 1", "The set of final states"], 1,
        "Σ* is the set of all possible strings (of any finite length, including zero) over the alphabet Σ."),
      q("A formal language is:",
        ["A programming language only", "A set of strings over an alphabet", "A single string", "A state diagram"], 1,
        "A language L is any subset of Σ*, for example all binary strings that end with 1."),
      q("A DFA is formally defined by which 5-tuple?",
        ["(Q, Σ, δ, q0, F)", "(S, T, P, R, E)", "(N, A, L, G, Z)", "(Q, δ, A, B, C)"], 0,
        "Q = states, Σ = input alphabet, δ = transition function, q0 = start state, F = set of accepting (final) states."),
      q("Which property is TRUE for every DFA?",
        ["Some states may have no transition for a symbol", "Each state has exactly one transition for each input symbol", "It may move on ε without reading input", "It has no start state"], 1,
        "A DFA is deterministic: for every state and every symbol there is exactly one next state."),
      q("Which feature is allowed in an NFA but NOT in a DFA?",
        ["A start state", "Multiple possible next states for the same state and symbol", "Accepting states", "An input alphabet"], 1,
        "An NFA may have zero, one, or several transitions on the same symbol from one state."),
      q("An ε-NFA (epsilon-NFA) can:",
        ["Move to another state without consuming any input symbol", "Only accept the empty string", "Have no states", "Read two symbols at once"], 0,
        "ε-transitions let the automaton change state \"for free\" without reading input."),
      q("Which statement about the power of DFAs and NFAs is correct?",
        ["NFAs recognize more languages than DFAs", "DFAs recognize more languages than NFAs", "Both recognize exactly the regular languages", "Neither recognizes any language"], 2,
        "NFAs are often easier to design, but every NFA can be converted to an equivalent DFA, so both accept exactly the regular languages."),
      q("Which method converts an NFA into an equivalent DFA?",
        ["Thompson's construction", "Subset construction", "Pumping lemma", "Parsing"], 1,
        "Subset construction makes each DFA state represent a set of NFA states."),
      q("In the worst case, an NFA with n states can require how many DFA states?",
        ["n", "2n", "n squared", "2^n"], 3,
        "A DFA state is a subset of NFA states, and a set of n elements has 2^n subsets."),
      q("What does the regular expression a* describe?",
        ["Exactly one a", "Zero or more occurrences of a", "One or more occurrences of a", "The letter a followed by a star symbol"], 1,
        "The Kleene star allows repetition any number of times, including zero, so a* matches ε, a, aa, aaa, and so on."),
      q("Which string is NOT in the language of the regular expression a(b|c)* ?",
        ["a", "abcb", "acc", "ba"], 3,
        "Every string in this language must start with a, followed by any number of b's or c's. \"ba\" starts with b, so it is not accepted."),
      q("Thompson's construction is used to:",
        ["Convert a DFA into a regular expression", "Convert a regular expression into an ε-NFA", "Minimize a DFA", "Test whether a language is finite"], 1,
        "Thompson's construction builds an ε-NFA piece by piece from a regular expression using union, concatenation, and Kleene star."),
      q("What is the purpose of a transition table?",
        ["To list the next state for each state and input symbol", "To count the number of strings", "To store the alphabet only", "To draw the regular expression"], 0,
        "A transition table shows δ in table form: rows are states, columns are input symbols, and each cell gives the next state(s)."),
      q("A string is accepted by a finite automaton if:",
        ["It is shorter than 10 symbols", "After reading the whole string, the automaton is in an accepting (final) state", "It passes through the start state", "It contains the symbol 0"], 1,
        "Acceptance depends on where the machine ends after consuming the entire input string."),
      q("A DFA over {0,1} has states q0 (start) and q1 (accepting). On input 1 it goes to q1; on input 0 it goes to q0 (from either state). Which language does it accept?",
        ["Strings that start with 1", "Strings that contain at least one 0", "Strings that end with 1", "Strings of even length"], 2,
        "The machine is in q1 exactly when the last symbol read was 1, so it accepts strings ending with 1."),
      q("Which regular expression describes all binary strings that start with 1?",
        ["1(0|1)*", "(0|1)*1", "0(0|1)*", "1*0*"], 0,
        "The string must begin with 1 and may be followed by any binary string, which is 1(0|1)*.")
    ]
  },

  /* =================== 5. INTERNET AND ADVANCED WEB TECHNOLOGIES =================== */
  "internet-web-technologies": {
    name: "Internet and Advanced Web Technologies",
    questions: [
      q("Which statement correctly describes the relationship between the Internet and the World Wide Web?",
        ["They are exactly the same", "The Web is a service that runs on top of the Internet", "The Internet runs on top of the Web", "The Web is hardware"], 1,
        "The Internet is the global network of networks. The Web is one service on it (others include email and file transfer)."),
      q("Who is credited with inventing the World Wide Web?",
        ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Linus Torvalds"], 1,
        "Tim Berners-Lee proposed the Web in 1989 and created the first browser and server at CERN."),
      q("What is the main role of a web browser?",
        ["Store websites permanently", "Request web resources and display them to the user", "Assign IP addresses", "Provide Internet service"], 1,
        "Browsers such as Chrome and Firefox send HTTP requests and render the returned HTML, CSS, and JavaScript."),
      q("What does a web server do?",
        ["Displays pages on the user's screen", "Stores web content and responds to client requests", "Translates domain names", "Repairs broken links"], 1,
        "Web servers (like Apache or Nginx) receive HTTP requests and send back pages, images, or data."),
      q("HTML stands for:",
        ["HyperText Markup Language", "High Tech Modern Language", "Hyperlink and Text Management Logic", "Home Tool Markup Language"], 0,
        "HTML is the markup language that defines the structure and content of web pages."),
      q("Which HTML tag defines the most important (largest) heading?",
        ["<head>", "<h6>", "<h1>", "<title>"], 2,
        "<h1> is the top-level heading. <h6> is the smallest. <head> and <title> are not page headings."),
      q("Which HTML code creates a hyperlink?",
        ["<link>page.html</link>", "<a href=\"page.html\">Click</a>", "<url=\"page.html\">", "<href>page.html</href>"], 1,
        "The anchor element <a> with an href attribute creates a link."),
      q("Which of the following is a semantic HTML5 element?",
        ["<div>", "<span>", "<article>", "<b>"], 2,
        "Semantic elements such as <article>, <nav>, <header>, and <footer> describe the meaning of their content. <div> and <span> are generic."),
      q("CSS stands for:",
        ["Computer Style Sheets", "Cascading Style Sheets", "Creative Styling Syntax", "Coded Server Scripts"], 1,
        "CSS controls the presentation of HTML: colors, fonts, spacing, and layout."),
      q("Which CSS selector targets elements with class=\"card\"?",
        ["#card", "card", ".card", "*card"], 2,
        "A dot selects a class (.card). A hash selects an id (#card)."),
      q("In the CSS box model, which order is correct from the INSIDE to the OUTSIDE?",
        ["Margin, border, padding, content", "Content, padding, border, margin", "Padding, content, margin, border", "Content, border, padding, margin"], 1,
        "Content is surrounded by padding, then the border, and finally the margin."),
      q("What is CSS Flexbox mainly used for?",
        ["Connecting to databases", "Arranging items in a flexible one-dimensional layout (row or column)", "Encrypting data", "Creating animations only"], 1,
        "Flexbox (display: flex) makes it easy to align and distribute space among items in a row or column."),
      q("What is JavaScript mainly used for on web pages?",
        ["Adding interactivity and dynamic behavior", "Defining page structure only", "Managing the physical network", "Registering domain names"], 0,
        "JavaScript runs in the browser to respond to clicks, validate forms, update the page, and communicate with servers."),
      q("Which JavaScript keyword declares a variable that cannot be reassigned?",
        ["var", "let", "const", "static"], 2,
        "const creates a binding that cannot be reassigned. let allows reassignment and var is the older function-scoped form."),
      q("What are the default ports for HTTP and HTTPS?",
        ["21 and 22", "80 and 443", "25 and 110", "443 and 80"], 1,
        "HTTP uses port 80 and HTTPS uses port 443 by default."),
      q("What does HTTPS add compared with HTTP?",
        ["Faster images", "Encryption of data in transit using TLS", "Free hosting", "Automatic backups"], 1,
        "HTTPS wraps HTTP in TLS so data cannot easily be read or changed by someone intercepting the connection."),
      q("Which HTTP status code means \"Not Found\"?",
        ["200", "301", "404", "500"], 2,
        "200 = OK, 301 = moved permanently, 404 = not found, 500 = internal server error."),
      q("What does DNS do?",
        ["Encrypts web traffic", "Translates domain names into IP addresses", "Stores user passwords", "Designs web pages"], 1,
        "DNS (Domain Name System) works like a phone book: it turns names like example.com into IP addresses."),
      q("In client-server architecture:",
        ["Clients request services and servers provide them", "Servers request services from clients only", "There are no servers", "Clients and servers must be the same machine"], 0,
        "A browser (client) sends a request and a server sends a response."),
      q("Cross-site scripting (XSS) is an attack in which:",
        ["The attacker physically steals the server", "Malicious scripts are injected into pages that other users view", "DNS is turned off", "The password is typed wrongly"], 1,
        "XSS happens when a site displays untrusted input without proper escaping. Prevent it by validating input and encoding output."),
      q("Which technique best protects a web application from SQL injection?",
        ["Using parameterized (prepared) queries", "Using shorter passwords", "Disabling CSS", "Hiding the login button"], 0,
        "Parameterized queries keep user input separate from SQL commands, so input cannot change the meaning of the query.")
    ]
  }
};
